### ISSUE TITLE
The voxels on the rear side of the vehicle seem to be neatly divided？

### ISSUE THREAD

**Issue by wy17646051** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#10]
I visualized the first sample of the mini dataset as shown in the image follow.
![image](https://user-images.githubusercontent.com/47509910/225345426-b9f873e9-d693-4c5a-bcce-7fdd166c0c47.png)
I found that the voxels on the rear side of the vehicle seem to be neatly divided (the positive direction of the z-axis in the figure corresponds to the negative direction of the y-axis of the lidar sensor in nuscenes), and other samples seem to be the same. That's the truth, or my fault for causing？

**Comment by 1349949** [comment]
That's the truth.
In fact, we limit the scope of the scene to within ±40m, which means that any object parts outside of this range are dropped.
