### ISSUE TITLE
About the relationship between voxel indexes and coordinates.

### ISSUE THREAD

**Issue by wy17646051** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#12]
According to the [issue](https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/issues/8), I understand that voxel uses ego coordinates, but I still have doubts about the relationship between vexol index and coordinates.

![image](https://user-images.githubusercontent.com/47509910/225602635-385db38c-70ee-4a2e-b5b3-308263ce02bb.png)

As shown in the above picture, In the ego coordinate system, the position of the [0,0,0] voxel relative to the coordinate (0,0,0) belongs to which one in the above picture, or neither.

**Comment by ChonghaoSima** [comment]
(b)

**Comment by zehuichen123** [comment]
Hi @ChonghaoSima, if (b) is right, how do the GTs lie in the (-40, 40) range? if the left and right part is symmetric, the number of voxels should be a 2n +1, rather 2n. However, the final annotation is 200x200, which confused me.

**Comment by yanchi-3dv** [comment]
> how do the GTs lie in the (-40, 40) range? 
Hi, I want to ask if you have the answer to this part?

**Comment by focus-on-11-road** [comment]
您的来信已收到，非常感谢！我将尽快对您的来信给予回复，祝您工作生活愉快！
                                                  刘宇杰
