### ISSUE TITLE
Is this occupancy network camera dataset much smaller than the original dataset?

### ISSUE THREAD

**Issue by sinsin1998** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#14]
I check that the dataset you provided is just about 32G, and the original nuscenes is about 450G?

**Comment by Yuhang-Lu** [comment]
Original nuScenes datasets contain more data, such as the LiDAR point cloud. But I think the images provided are the same as the original dataset.

**Comment by ChonghaoSima** [comment]
Original nuscenes dataset contains a lot of sweep data, which we removed for simplicity

**Comment by Rayn-Wu** [comment]
> Original nuscenes dataset contains a lot of sweep data, which we removed for simplicity

Does it mean we do not need sweeps data for occupancy task？

**Comment by focus-on-11-road** [comment]
您的来信已收到，非常感谢！我将尽快对您的来信给予回复，祝您工作生活愉快！
                                                  刘宇杰
