### ISSUE TITLE
Data prepare

### ISSUE THREAD

**Issue by monoavatar** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#15]
Hi, 

I'm not familiar with bevformer.  When I prepare the data folder following the instruction, I find there is no information about how to get the `v1.0-trainval` folder in `data/occ3d-nus/`. Is this folder empty? If not, how can I get the files in `v1.0-trainval` folder?

Thanks for your help!

**Comment by nzpaul97** [comment]
Did you solve this problem? 

Can you help me? Because I'm having the same problem.

Thanks
