### ISSUE TITLE
GPU Memory Consumption

### ISSUE THREAD

**Issue by monoavatar** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#16]
Hi,

It would be helpful if anyone could tell me the **least GPU memory consumption** during training and testing the base BEVFormer-Occ model.

Thanks a lot!

**Comment by ChonghaoSima** [comment]
Are you asking the base version(R101-DCN) of BEVFormer-Occ or the small version?

For the small version, the max GPU memory consumption is around 17G. We recommend 3090 as the baseline GPU.

**Comment by cdb342** [comment]
> Are you asking the base version(R101-DCN) of BEVFormer-Occ or the small version?
> 
> For the small version, the max GPU memory consumption is around 17G. We recommend 3090 as the baseline GPU. For the base version, the max GPU memory consumption is around 28G. We recommend V100 as the baseline GPU. Or you can try to shrink the channel number to save GPU memory

What about the training time?

**Comment by ChonghaoSima** [comment]
> > Are you asking the base version(R101-DCN) of BEVFormer-Occ or the small version?
> > For the small version, the max GPU memory consumption is around 17G. We recommend 3090 as the baseline GPU. For the base version, the max GPU memory consumption is around 28G. We recommend V100 as the baseline GPU. Or you can try to shrink the channel number to save GPU memory
> 
> What about the training time?

Small roughly 1-2 days
Base roughly 2-3 days
