### ISSUE TITLE
The voxel GTs do not aglin well with the images?

### ISSUE THREAD

**Issue by shikongzxz** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#18]
I project the centers of voxels to the corresponding image, and find that it does not align well with the image. Refering to the image below: 
![image](https://user-images.githubusercontent.com/9074832/228173552-efa35b96-1016-46b2-ae35-6e48be3d8594.png)

Take a look at the person in the image, according to voxels, it is 7 * 0.4 = 2.8m high. Is that reasonable?

I used the "voxel to points" function from here: https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/blob/main/utils/vis.py#L36
And camera intrinsics and extrinsics from the "annotation.json" file.
Please tell me if I missed anything.

**Comment by shikongzxz** [comment]
I am not counting the pixels, but the voxels which are projected to the image. If you doubt that, you can visualize the GT file `mini/gts/scene-0061/ca9a282c9e77460f8360f564131a8af5/labels.npz`, it gives this image:
![image](https://user-images.githubusercontent.com/9074832/228195379-2ea9cad5-d1fa-459a-a44f-bb37dd4b32e4.png)

the pink voxels, which stands for a person, it occupies 7 voxels.

P.S. I used the following code to project the center of the voxels to the image:
```python
    meta_file = "annotations.json"
    with open(meta_file, 'r') as f:
        meta = json.load(f)

    scene_name = meta["train_split"][0]
    scene_info = meta["scene_infos"][scene_name]

    color_map = get_color_map_nuscenes_seg()

    frame_info = next(iter(scene_info.values()))
    timestamp = frame_info["timestamp"]
    ts_save_path = os.path.join(save_dir, str(timestamp))
    os.makedirs(ts_save_path, exist_ok=True)

    voxel_gt_file = os.path.join(data_root, frame_info["gt_path"])
    voxel_gt = np.load(voxel_gt_file)
    voxel_semantics = voxel_gt["semantics"]
    mask_lidar = voxel_gt["mask_lidar"]
    mask_camera = voxel_gt["mask_camera"]
    grid_shape = voxel_semantics.shape
    voxel_center, voxel_semantics = voxel2points(
        voxel_semantics, [voxel_size] * 3)
    voxel_center = voxel_center.numpy()
    voxel_semantics = voxel_semantics.numpy()
    print(voxel_center.shape)
    print(voxel_semantics.shape)

    # rander each image view
    for cam_name, cam_info in frame_info["camera_sensor"].items():
        img = cv2.imread("imgs/"+cam_info["img_path"])
        print(cam_info["img_path"])
        img_h, img_w = img.shape[:2]
        K = np.array(cam_info["intrinsics"])
        # get camera horizontal fov, if not given
        fov_half = get_horizontal_fov(img_w, K)
        print(f"Half of fov of {cam_name} is {fov_half}")

        extrinsic = cam_info["extrinsic"]
        T_ego2camera = transform_matrix(
            np.array(extrinsic['translation']),
            Quaternion(extrinsic['rotation']),
            inverse=True,
        )
        pts = np.concatenate([voxel_center,
                              np.ones((voxel_center.shape[0], 1))], axis=-1)
        pts = np.squeeze(np.matmul(T_ego2camera[None, :, :],
                                   pts[:, :, None]))
        pts = pts[:, :3]
        alpha = np.abs(np.arctan2(pts[:, 0], pts[:, 2]))
        view_mask = alpha < fov_half
        pts = pts[view_mask]
        view_sematics = voxel_semantics[view_mask]

        pts = np.squeeze(np.matmul(K[None, :, :],
                                   pts[:, :, None]))
        pts /= pts[:, [2]]
        pts = pts.astype(int)
        for i in range(pts.shape[0]):
            if 0 < pts[i, 0] < img_w and 0 < pts[i, 1] < img_h:
                color = [int(color_map[view_sematics[i], j]) for j in
                         range(2, -1, -1)]
                cv2.circle(img, (pts[i, 0], pts[i, 1]), 1, color, -1)

        cv2.imwrite(os.path.join(ts_save_path, f"{cam_name}.jpg"), img)
```

**Comment by waveleaf27** [comment]
Hi [shikongzxz](https://github.com/shikongzxz), 
The deviation in height is caused by voxelization and the lack of translation in the z-axis. This means that the height of an object, after aggregating all frames, may be larger than its true value.
As we do not have access to the original data, this deviation is considered acceptable in this competition. However, we plan to collaborate with the official team of nuscene to address the pose issue after the competition.

**Comment by shikongzxz** [comment]
Thanks for replying. Looking forward to a better version of the data :)

**Comment by qifeng22** [comment]
Hi! I have a question about the coordinate convention used for the OCC ground-truth (GT) labels.

I understand that the OCC GT is provided in the ego coordinate frame. However, when I generate my own occupancy in the ego frame, the coordinate origin seems to end up on the ground plane, while the GT labels appear to use a different origin (there seems to be a vertical offset between my OCC and the GT). Could you clarify where the OCC GT’s origin is defined?

<img width="1282" height="705" alt="Image" src="https://github.com/user-attachments/assets/02ef91a8-8c5a-46e6-af83-b813be0763f9" />

gt
<img width="1760" height="957" alt="Image" src="https://github.com/user-attachments/assets/36022660-08a4-4051-8103-19ad04dcdb66" />
@waveleaf27

**Comment by focus-on-11-road** [comment]
您的来信已收到，非常感谢！我将尽快对您的来信给予回复，祝您工作生活愉快！
                                                  刘宇杰

**Comment by qifeng22** [comment]
I also have a question about the nuScenes ego frame:
Isn’t the ego coordinate origin supposed to be aligned with the ground plane (i.e., z=0 at ground level)? In my GT visualization, the origin appears above the ground. Is this expected? If so, is the ego frame origin defined at the vehicle’s ego/IMU pose height rather than at the ground? What is the exact vertical offset relative to the ground (or to the LiDAR sensor)?
