### ISSUE TITLE
Do we need to predict the free voxel?

### ISSUE THREAD

**Issue by Yuhang-Lu** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#20]
I notice that there is no result for the “free” class (label 17) in the baseline results provided, is this category not required for calculating the mIoU?

**Comment by OrangeSodahub** [comment]
@Yuhang-Lu Need to predict the `free` voxel, the baseline just not print the result of `free`, but predicted it.

**Comment by waveleaf27** [comment]
The 'free' category does not participate in metric calculation and does not affect the ranking. @Yuhang-Lu
