### ISSUE TITLE
If all nuScenes, nuScenes-lidarseg and nuImages annotations are allowed to use during training?

### ISSUE THREAD

**Issue by ifiwill** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#21]
If all nuScenes, nuScenes-lidarseg and nuImages annotations are allowed to use during training?

Thanks!

**Comment by waveleaf27** [comment]
Yep! Feel free to use the corresponding box and segmentation annotations in this dataset, but avoid using any other data such as Waymo for pretraining.
