### ISSUE TITLE
Error when training with fp16

### ISSUE THREAD

**Issue by FresherQ** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#22]
Hi,
1. I'm trying to train bevformer_small_occ with fp16 but failed.
I add `fp16 = dict(loss_scale=512.)` in config and warp the model to fp16 in train.py using following codes.
```
    model = build_model(
        cfg.model,
        train_cfg=cfg.get('train_cfg'),
        test_cfg=cfg.get('test_cfg'))
    
    # wrap the model to fp16
    fp16_cfg = cfg.get('fp16', None)
    if fp16_cfg is not None:
        wrap_fp16_model(model)

    model.init_weights()
```
Follow the getting_started.md, the training process failed with following error.
![1680267950902](https://user-images.githubusercontent.com/114493066/229127951-808aa335-1c58-4160-8e25-4f868744962b.png)

2. I also wonder is it possible to provide an official guide or implementation of fp16 training?

**Comment by waveleaf27** [comment]
Try to add 'find_unused_parameters=True' in your config file.
