### ISSUE TITLE
About the `gts` semantics in labels

### ISSUE THREAD

**Issue by OrangeSodahub** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#23]
I tried to visualize the semantics in `gts` and got one of them:
![image](https://user-images.githubusercontent.com/54439582/229261154-32b6b737-186b-4ebf-ae08-7f1093aad3ff.png)
![image](https://user-images.githubusercontent.com/54439582/229261166-664e0a2c-030f-4fae-9afa-ffb1e626c4f8.png)

I have removed the voxels which are labeled in `mask_lidar` and `mask_camera`, so is it right? It looks like something wrong with so many whith cubes. And could you provide the official guidance of the visualization?

**Comment by OrangeSodahub** [comment]
Solved, thanks!

**Comment by LHY-HongyangLi** [comment]
> 

Hi @OrangeSodahub, I also meet this problem when I try to visualize camera_mask as shown below. Could you share your solution?
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/89394032/236981490-fa878643-8652-45a1-a0dd-9be064a2f44a.png">

**Comment by LHY-HongyangLi** [comment]
Oops... it's my fault. I used the mask inversely.
