### ISSUE TITLE
Is the `mask camera` mandatory in evaluatioin?

### ISSUE THREAD

**Issue by OrangeSodahub** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#24]
I noticed that your baseline config gives `use_mask` to `False`, that means you didn't you any mask (neither `mask_lidar` nor `mask_camera`) when evaluation and loss calculation, so is this config mandatory? or we could set them freely?

**Comment by waveleaf27** [comment]
Both [mask_lidar] and [mask_camera] masks are optional for training. Participants do not need to predict the masks. Only [mask_camera] is used for evaluation; the unobserved voxels are not involved during calculating mIoU.
