### ISSUE TITLE
Where can I get the gts folder and annotation.json? thanks

### ISSUE THREAD

**Issue by Yuankus** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#25]
I can't find them in https://www.nuscenes.org/download ,or maybe in other names?

**Comment by waveleaf27** [comment]
You can donwload gt from google drive or Baidu yun, the download url can been found in README.

**Comment by Yuankus** [comment]
hi, first of all, thanks for your help! I solved previous problem and I successfully run the training. However I found maybe something was wrong while training. I used 'ckpts/r101_dcn_fcos3d_pretrain.pth' but got lots of missing keys(show in pictures). Is it normal? Could you please help me, thanks again!
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        4/1/2023 19:20
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction] Where can I get the gts folder and annotation.json? thanks (Issue #25)
        
      
    
  

Closed #25 as completed.
