### ISSUE TITLE
How can i get the "v1.0-trainval" ?

### ISSUE THREAD

**Issue by PungTeng** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#28]
I have put the imgs.tar.gz into the "samples". Need me to down the "v1.0-trainval" data from https://www.nuscenes.org/download ?

**Comment by waveleaf27** [comment]
Hi, the 'imgs' datas have the same hierarchy with the image samples in the original nuScenes dataset.  You do not need me to down the "v1.0-trainval" data again.
