### ISSUE TITLE
TypeError: NuSceneOcc: Unsupported format: None

### ISSUE THREAD

**Issue by hitcslj** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#3]
Hello there! I was hoping to ask for some assistance with an issue I'm encountering. I've successfully utilized the [TPVFormer](https://github.com/wzzheng/TPVFormer)  environment, but I'm now facing an error message when attempting to transfer it to another project. Specifically, the error reads "TypeError: NuSceneOcc: Unsupported format: None". Would you happen to have any suggestions on how to resolve this? Thank you for your help in advance!

**Comment by hitcslj** [comment]
Resolve the issue by creating a new conda environment based on the installation steps of [bevformer](https://github.com/fundamentalvision/BEVFormer/blob/master/docs/install.md)!And modified some.
Here are my installation instructions:
```bash
conda create -n open-mmlab python=3.8 -y
conda activate open-mmlab

pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html
# Recommended torch>=1.9

conda install -c omgarcia gcc-6 # gcc-6.2

pip install mmcv-full==1.4.0
#  pip install mmcv-full==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html

pip install mmdet==2.14.0
pip install mmsegmentation==0.14.1

git clone https://github.com/open-mmlab/mmdetection3d.git
cd mmdetection3d
git checkout v0.17.1 # Other versions may not be compatible.
pip install -e .

pip install timm
pip install simplejson

pip install setuptools==59.5.0

```

**Comment by YoushaaMurhij** [comment]
I am using the same environment inside docker but the problem still exists!

**Comment by cdb342** [comment]
`    
        data = mmcv.load(ann_file, file_format='pkl')
`

This can be solved by adding `file_format='pkl'` in nuscenes_occ.py
