### ISSUE TITLE
Where can I download v1.0-trainval?

### ISSUE THREAD

**Issue by codename1995** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#31]
Hi,

thank you for your great work to organize such a challenge.

I follow the [getting_started](https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/blob/main/docs/getting_started.md) guideline to prepare the dataset. However, I ran into a error:

`FileNotFoundError: [Errno 2] No such file or directory: './data/occ3d-nus/v1.0-trainval/attribute.json'`

Although it is mentioned that v1.0-trainval is not necessary to download in issue #28 , this error indicates a missing file in that dir. So I go to the [nuscenes downloads](https://www.nuscenes.org/download), but there are too many files to check. I tried these files:
1. nuImages -- All -- Metadata --> nuimages-v1.0-all-metadata.tgz. But the files inside are split to train and val. And they are json files so they are not easy to merge.
2. nuScenes-lidarseg -- All -- Metadata and sensor file blobs --> nuScenes-lidarseg-all-v1.0.tar. There is a subfolder named as v1.0-trainval, but I can not find the file attribute.json.

Could you explicitly let me know where I can obtain the v1.0-trainval?

Thanks in advance.

**Comment by gsg213** [comment]
hello @codename1995,

In nuScenes download, you need the metadata from Full dataset (v1.0) / trainval.

**Comment by codename1995** [comment]
> hello @codename1995,
> 
> In nuScenes download, you need the metadata from Full dataset (v1.0) / trainval.

I tried Full dataset (v1.0) -- Trainval -- Metadata --> v1.0-trainval_meta.tgz. It works. Thanks!
