### ISSUE TITLE
Why do I take lidarseg points in the altitude direction -1 to 5.4 and they don't align to provided 'gts'?

### ISSUE THREAD

**Issue by LH-WA** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#36]
For example, the lidarseg points within range -1 to 5.4 cannot detect the ground, What height range of lidarseg is used to generate 'gts'? Thanks!

**Comment by waveleaf27** [comment]
Hi, the Occ ground truth in Vehicle coors, while the LiDAR points in LiDAR coors.

**Comment by LH-WA** [comment]
Thank you for your reply. I got it !
