### ISSUE TITLE
Submission Format

### ISSUE THREAD

**Issue by oblivious137** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#37]
What format should we submit our results in?

**Comment by OrangeSodahub** [comment]
I wonder too

**Comment by cnstark** [comment]
+1

**Comment by ChonghaoSima** [comment]
The test server will be available on next Monday (5.8), the detailed submission format would be available at that time. Please stay tuned.

**Comment by OrangeSodahub** [comment]
@ChonghaoSima  Any news? It looks like no updating, thanks.

**Comment by tongwwt** [comment]
Sorry for the delay of test server.  The test server has been submmited into EvalAI, and it will be available in the website(https://eval.ai/web/challenges/challenge-page/2045) with the approval from EvalAI. The approval from EvalAI may need some time. Please be patient. The submission format will be updated in the GitHub（https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction）once the test serve is available.

**Comment by 1349949** [comment]
The submission format has been updated.

**Comment by oblivious137** [comment]
Thanks.
