### ISSUE TITLE
Which timestamp (sweep or camera) the `occ_gt` lies in?

### ISSUE THREAD

**Issue by OrangeSodahub** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#38]
As you said the `occ_gt` lies in the ego coordinates, but both the timestamp of the sweep and the camera have the ego coordinates, I wonder it's in the timestamp of the sweep or of the camera? If camera, which camera? Thanks.

The ego poses in different cameras also have small differences.

**Comment by waveleaf27** [comment]
In practice, lidar timestamp is used. 
This is a very good question. If there is a significant performance gap between using lidar timestamp and camera timestamp during evaluation, please report HERE. @OrangeSodahub

**Comment by OrangeSodahub** [comment]
Thanks
