### ISSUE TITLE
Why permute h&w in 3d decoder?

### ISSUE THREAD

**Issue by LMerCy** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#39]
You permute  voxel feature to N * W * H * pillar_h * C(0,4,3,2,1), why not N * H * W * pillar_h * C(0,3,4,2,1)? Does it matter?
https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/blob/7816c17577a46d95e25510c3803f1d6534e4f294/projects/mmdet3d_plugin/bevformer/modules/transformer_occ.py#L338-L341

**Comment by waveleaf27** [comment]
Hi, this is done in order to match the HW order of the ground truth (GT).
