### ISSUE TITLE
BEVDet baseline with 42 mIOU

### ISSUE THREAD

**Issue by HuangJunJie2017** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#40]
We support the occupancy prediction task with the BEVDet codebase and offer a strong baseline with performance up to 42.0 mIOU:

| Config                                                                    | mIOU      | GPU Consumption| 
| ----------------------------------------------------- | ---------- | --------------------|
| bevformer_base_occ  | 23.7     | 645.3 GPUHours |
| [**BEVDet-Occ-R50-4D-Stereo-2x**](https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/configs/bevdet_occ/bevdet-occ-r50-4d-stereo-24e.py)  | 36.1     | 132.0 GPUHours |
| [**BEVDet-Occ-STBase-4D-Stereo-2x**](https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/configs/bevdet_occ/bevdet-occ-stbase-4d-stereo-512x1408-24e.py)                            | 42.0     | 531.2 GPUHours |

GPU Consumption  is measured on GTX 3090

**Comment by waveleaf27** [comment]
Great work !

**Comment by 0w0h0y** [comment]
I wonder what's the major factor for this strong performance, since BEVFormer shows basically flat performance with BEVDet on detection tasks.

**Comment by HuangJunJie2017** [comment]
@0w0h0y Using the camera mask in calculating loss is the main reason. In fact, training BEVFormer with the camera mask in calculating loss can also improve performance to a large extend. For example, training BEVFormer-Base with the camera mask, it scores 33. 4 mIOU at epoch 4:
```
===> per class IoU of 6019 samples:
===> others - IoU = 5.51
===> barrier - IoU = 42.75
===> bicycle - IoU = 10.26
===> bus - IoU = 40.46
===> car - IoU = 49.09
===> construction_vehicle - IoU = 15.41
===> motorcycle - IoU = 14.86
===> pedestrian - IoU = 23.71
===> traffic_cone - IoU = 21.18
===> trailer - IoU = 26.41
===> truck - IoU = 33.04
===> driveable_surface - IoU = 79.69
===> other_flat - IoU = 35.28
===> sidewalk - IoU = 47.6
===> terrain - IoU = 50.23
===> manmade - IoU = 39.02
===> vegetation - IoU = 32.7
===> mIoU of 6019 samples: 33.37
```
Other than that, I haven't done a detailed ablation study on other factors between the two paradigms.
