### ISSUE TITLE
Is there any inference code for visualize predicted result?

### ISSUE THREAD

**Issue by joonsu0109gh** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#41]
As far as I understand, your visualization code is only capable of visualizing the existing .npz file in the dataset.

I wonder if there is any inference code to visualize the predicted result and save the predicted result.

**Comment by ChonghaoSima** [comment]
You can directly use the visualization code on your predicted numpy array. For saving the predicted result, np save is recommended.
