### ISSUE TITLE
What coordinate system is the occ gts in?

### ISSUE THREAD

**Issue by promesse** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#43]
![image](https://user-images.githubusercontent.com/26239060/236592045-49d7b970-1c29-4b57-9545-329d4e82c50b.png)
If the gts is in the lidar coordinate system, is it possible that -1 didn't reach the ground?

**Comment by ChonghaoSima** [comment]
please refer to https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/issues/8
