### ISSUE TITLE
About the usage specification of mask camera

### ISSUE THREAD

**Issue by jiemosang** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#44]
1. Can the mask camera be used as input to the network?
2. Is the mask camera provided during the test phase?

**Comment by ChonghaoSima** [comment]
1. No
2. No

**Comment by zzy-ucas** [comment]
> 1. No
> 2. No

Why the answer 2 is `No`? I am confused. Mask camera is optional for calculating train loss and is forced to be used for calculating IOU in the train/val/test phase, isn't it?
