### ISSUE TITLE
Can baseline code support fp16?

### ISSUE THREAD

**Issue by Watebear** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#45]
Hello, I try to run the baseline code, but don't have gpus like 3090 which has 24g memory.
Could you help me, please.

**Comment by ChonghaoSima** [comment]
You could try the code in BEVFormer to open fp16, but we haven't test on this.

**Comment by Watebear** [comment]
I tried， but met errors. Thanks.

**Comment by Watebear** [comment]
it works.

**Comment by qihao-plus** [comment]
How?
