### ISSUE TITLE
Regarding the rule

### ISSUE THREAD

**Issue by cdb342** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#46]
I noticed that the rule regarding restrictions on the use of other datasets has been removed. Does this mean that it is now permissible to use other public or private datasets?

**Comment by cdb342** [comment]
> I noticed that the rule regarding restrictions on the use of other datasets has been removed. Does this mean that it is now permissible to use other public or private datasets?
<img width="1006" alt="1683539069246" src="https://user-images.githubusercontent.com/61510717/236792787-d18188c3-5d57-4a8e-8258-b9cd31804cad.png">

**Comment by faikit** [comment]
Hi, for details please refer to the [updated rules](https://opendrivelab.com/AD23Challenge.html#rules). Private data is not allowed.
