### ISSUE TITLE
When will you release test dataset

### ISSUE THREAD

**Issue by Watebear** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#47]
Hello,  the test dataset is not is nt avaliable. When can we get it?

**Comment by ChonghaoSima** [comment]
Some unexpected fail on the test server uploading process, we are working with EvalAI team and rushing to fix this, please stay tuned 🙏

**Comment by tongwwt** [comment]
The test server has been submmited into EvalAI, and it will be available in the website(https://eval.ai/web/challenges/challenge-page/2045) with the approval from EvalAI. The approval from EvalAI may need some time. Please be patient and it will be updated in the GitHub（https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction) once the test server is available.

**Comment by 1349949** [comment]
The test dataset has been released, and the test server is available!
