### ISSUE TITLE
Bug in nuscenes_dataset.py

### ISSUE THREAD

**Issue by Isaac-xie** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#49]
hi, When I was single-stepping, I found that in nuscene_dataset.py, line 212, rotation is assigned as a quaternion.
assigning a quaternion to a list results in only the first value being assigned. like this
![{b5d659c8-4d80-4476-8f8e-87399552f9e7}](https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/assets/83942224/2b9c7173-dc8b-47ed-b516-7bf8917996ea)

**Comment by tongwwt** [comment]
Hi, can you describe your question in detail? The rotation matrix is equivalent to the quaternion when defining the transformation matrix.

**Comment by tongwwt** [comment]
Please check again the lin208-212 in https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/blob/HEAD/projects/mmdet3d_plugin/datasets/nuscenes_dataset.py#L208-L212
The original translation and rotation in can bus has been replaced with ego2global transformation.
`rotation = Quaternion(input_dict['ego2global_rotation'])
translation = input_dict['ego2global_translation']
can_bus = input_dict['can_bus']
can_bus[:3] = translation
can_bus[3:7] = rotation`

**Comment by Isaac-xie** [comment]
@tongwwt 
hi，I have not modified any code in nuscenes_dataset.py. If you run it without the above problem, is there a problem with the version of Quaternion？

**Comment by tongwwt** [comment]
Hi, I check the code. The  can_bus[3:7]  only keeps the information of roatation angle which can represent the quaternion, causing the problem you provides. This type of definition does not affect the model performance.
