### ISSUE TITLE
The frame number of test split is 6008?

### ISSUE THREAD

**Issue by Wallong** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#50]
Hello, I'm using the script `tools/create_data.py` to generate the info file for test split.

But the showed number of frames is **6008**, which does not match the **6006** written in the doc [getting_started.md](https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/blob/main/docs/getting_started.md).  

I would like to confirm if the doc was written incorrectly or if there is a problem with my local file?

@ChonghaoSima @tongwwt @waveleaf27 

![328cd814096da1b69cbb14b3fe86b2b](https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/assets/13499067/0275c09d-a6d2-4a4c-9008-8852d69e543a)

![4db66213a63221eeff0538ec0199bcc](https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/assets/13499067/17294b05-b4ec-4ac4-a0f6-41fb69ceb115)

**Comment by ChonghaoSima** [comment]
It's 6008, and we will fix the typo in the doc
