### ISSUE TITLE
i can't test using baseline

### ISSUE THREAD

**Issue by sumonky** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#53]
I download r101_dcn_fcos3d_pretrain.pth. And when i run the test command in get_started.md，an error occured.
`./tools/dist_test.sh projects/configs/bevformer/bevformer_base_occ.py work_dirs/bevformer_base_occ/r101_dcn_fcos3d_pretrain.pth 8`
![image](https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/assets/71999136/44350e94-7993-4cd7-8fa1-73d1bd75fa34)
And when i generate the submission using pretrained model,the miou is 0.
![image](https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/assets/71999136/24b215e0-e6f9-4a3a-bdf3-9d6dac30ed04)

**Comment by 1349949** [comment]
> I download r101_dcn_fcos3d_pretrain.pth. And when i run the test command in get_started.md，an error occured. `./tools/dist_test.sh projects/configs/bevformer/bevformer_base_occ.py work_dirs/bevformer_base_occ/r101_dcn_fcos3d_pretrain.pth 8` ![image](https://user-images.githubusercontent.com/71999136/241944733-44350e94-7993-4cd7-8fa1-73d1bd75fa34.png) And when i generate the submission using pretrained model,the miou is 0. ![image](https://user-images.githubusercontent.com/71999136/241945318-24b215e0-e6f9-4a3a-bdf3-9d6dac30ed04.png)

You can use this command to generate the submission files
`./tools/dist_test.sh projects/configs/bevformer/bevformer_base_occ_test.py work_dirs/bevformer_base_occ/epoch_24.pth 8 --format-only --eval-options 'submission_prefix=./occ_submission'`
