### ISSUE TITLE
About test dataset evaluation in the future

### ISSUE THREAD

**Issue by MiraclesinWang** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#57]
Hi, thx for your great contribution to occupancy prediction area. 
As the evaluation on eval.ai is over, may you open source for test dataset's ground truths or open another online judge in the future?

**Comment by hli2020** [comment]
Thanks for your interest. We would keep the test data **confidential** after the challenge. You can still submit the results on evalAI. If you want to expose your result on the official website, shoot us an email and we would post it on [opendrivelab.com](opendrivelab.com)

Yes, the Challenge **will** be back in 2024. We are still figuring out where to host the challenge, as evalAI is responding very slowly. Please stay tuned, or subsribe to our mailing list (please check here [opendrivelab.com](opendrivelab.com))

Thanks,
cc @ChonghaoSima @faikit

**Comment by ChonghaoSima** [comment]
@MiraclesinWang Hello, the evalai test server is re-opened. Please feel free to give a submission. Notably, if you would like to have your submission score being reflected on our leaderboard (https://opendrivelab.com/AD23Challenge.html#Track3), shoot us an email at contact@opendrivelab.com.
