### ISSUE TITLE
How to create .npz file

### ISSUE THREAD

**Issue by thanhpt93** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#63]
Hi author, I have dataset with demension and location of each object in image. How can I create or convert to groundtruth .npz file?
Thank you very much!

**Comment by focus-on-11-road** [comment]
您的来信已收到，非常感谢！我将尽快对您的来信给予回复，祝您工作生活愉快！
                                                  刘宇杰
