### ISSUE TITLE
Is voxels GT in lidar coordinate system?

### ISSUE THREAD

**Issue by shikongzxz** [CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction#8]
Hi, is voxels GT in lidar coordinate system or in ego-frame coordinate system?

Based on the code https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/blob/main/projects/mmdet3d_plugin/bevformer/modules/encoder.py#L126 here, it seems it is in ego-frame coordinate system, just to confirm.

Besides, can you provide the code that converts the voxel gird to real points in actual coordinate?

**Comment by 1349949** [comment]
It is in **ego** coordinate.
